version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:6.2
    volumes:
      - redis-data:/data

volumes:
  redis-data:
